# 7.17.9
filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
      hints.default_config.enabled: false
      templates:
        - condition:
            contains:
              docker.container.image: elk-demo
          config:
            - type: container
              enabled: true
              paths:
                - /var/lib/docker/containers/${data.docker.container.id}/*.log

# Write Filebeat own logs only to file to avoid catching them with itself in docker log files
logging.to_files: true
logging.to_syslog: false
logging.level: warning

output.logstash:
  enabled: true
  hosts: ["logstash:5044"]