# 7.17.9
filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
      hints.default_config.enabled: false
      templates:
        - condition:
            equals.docker.container.labels.filebeat_enable: "enabled"
          config:
            - type: container
              paths:
                - "/var/lib/docker/containers/*/*.log"
              fields_under_root: true

output.logstash:
  enabled: true
  hosts: ["logstash:5044"]